// OTO-RAPOR KAPSAMLI ARAÇ VERİ SETİ (TÜRKİYE PAZARI)
export const vehicleData = {
    "Otomobil": {
        "Alfa Romeo": { "Tonale": { "1.5 Hybrid": ["Sprint", "Veloce"], "1.6 Dizel": ["Sprint"] }, "Stelvio": { "2.0 280 HP": ["Veloce"] } },
        "Audi": { "A3": { "1.5 TFSI 150 HP": ["Advanced", "S Line"] }, "A4": { "2.0 TDI 204 HP": ["Advanced", "S Line"] }, "A6": { "2.0 TDI 204 HP": ["Advanced", "S Line"] } },
        "BMW": { "1 Serisi": { "118i": ["Sport Line", "M Sport"] }, "2 Serisi": { "218i Gran Coupé": ["Sport Line", "M Sport"] }, "3 Serisi": { "320i Sedan": ["M Sport"] }, "5 Serisi": { "520i Sedan": ["Luxury Line", "M Sport"] } },
        "Citroën": { "C3": { "1.2 PureTech": ["Feel Bold", "Shine"] }, "C4": { "1.2 PureTech 130 HP": ["Feel Bold", "Shine Bold"] }, "C4 X": { "1.2 PureTech 130 HP": ["Feel Bold", "Shine Bold"] }, "C5 Aircross": { "1.5 BlueHDi 130 HP": ["Shine Bold"] } },
        "Dacia": { "Sandero": { "1.0 TCe 90 HP": ["Essential", "Expression"] }, "Sandero Stepway": { "1.0 Turbo 90 HP": ["Essential", "Expression", "Extreme"] } },
        "Fiat": { "Egea Sedan": { "1.4 Fire 95 HP": ["Easy", "Urban", "Lounge"] }, "Egea Cross": { "1.4 Fire 95 HP": ["Street", "Urban", "Lounge"] } },
        "Ford": { "Fiesta": { "1.1L 75 PS": ["Style"] }, "Focus": { "1.5L EcoBoost 123 PS": ["Titanium", "ST-Line"] } },
        "Honda": { "City": { "1.5L VTEC": ["Elegance", "Executive"] }, "Civic": { "1.5L VTEC Turbo": ["Elegance", "Executive+"] } },
        "Hyundai": { "i10": { "1.0 MPI 67 PS": ["Jump", "Style", "Elite"] }, "i20": { "1.4 MPI 100 PS": ["Jump", "Style", "Elite"] }, "Elantra": { "1.6 MPI 123 PS": ["Style"] } },
        "Kia": { "Picanto": { "1.0L 67 PS": ["Feel", "Live", "Cool"] }, "Rio": { "1.4L 100 PS": ["Cool", "Elegance"] }, "Cerato": { "1.6L 128 PS": ["Elegance"] } },
        "Mercedes-Benz": { "A Serisi": { "A 200": ["AMG+"] }, "C Serisi": { "C 200 4MATIC": ["AMG"] }, "E Serisi": { "E 180": ["Exclusive", "AMG"] } },
        "MG": { "MG5": { "1.5 VTi-TECH": ["Comfort", "Luxury"] } },
        "Nissan": { "Micra": { "1.0 IG-T 92 PS": ["Visia", "Tekna"] } },
        "Opel": { "Corsa": { "1.2 75 HP": ["Elegance"], "1.2 130 HP": ["Ultimate"] }, "Astra": { "1.2 130 HP": ["Edition", "Elegance", "GS"] } },
        "Peugeot": { "208": { "1.2 PureTech 100 HP": ["Active Prime", "Allure Selection"] }, "308": { "1.2 PureTech 130 HP": ["Active Prime", "Allure"] }, "408": { "1.2 PureTech 130 HP": ["Allure", "GT"] } },
        "Porsche": { "Panamera": { "Panamera": ["Standart"] }, "Taycan": { "Taycan": ["Standart"] } },
        "Renault": { "Clio": { "1.0 TCe 90 HP": ["Equilibre", "Evolution", "Techno Esprit Alpine"] }, "Taliant": { "1.0 TCe 90 HP": ["Joy", "Touch"] } },
        "Seat": { "Ibiza": { "1.0 EcoTSI 110 HP": ["Style", "FR"] }, "Leon": { "1.5 eTSI 150 HP": ["FR"] } },
        "Skoda": { "Fabia": { "1.0 TSI 95 PS": ["Elite", "Premium"] }, "Scala": { "1.0 TSI 110 PS": ["Elite", "Premium"] }, "Octavia": { "1.5 TSI e-TEC 150 PS": ["Elite", "Premium"] } },
        "Toyota": { "Corolla": { "1.5": ["Vision Plus", "Dream", "Flame X-Pack", "Passion X-Pack"] } },
        "Volvo": { "S60": { "B5 2.0": ["Plus", "Ultimate"] }, "S90": { "B5 2.0": ["Plus", "Ultimate"] } },
    },
    "Arazi, SUV & Pickup": {
        "Audi": { "Q2": { "1.5 TFSI 150 HP": ["Advanced", "S Line"] }, "Q3": { "1.5 TFSI 150 HP": ["Advanced", "S Line"] } },
        "BMW": { "X1": { "sDrive18i": ["X-Line", "M Sport"] }, "X3": { "sDrive20i": ["X-Line", "M Sport"] } },
        "Chery": { "Omoda 5": { "1.6 TGDI": ["Comfort", "Luxury", "Excellent"] }, "Tiggo 7 Pro": { "1.6 TGDI": ["Comfort", "Luxury", "Excellent"] }, "Tiggo 8 Pro": { "1.6 TGDI": ["Luxury", "Excellent"] } },
        "Dacia": { "Duster": { "1.0 Turbo 90 HP": ["Expression"], "1.3 Turbo 150 HP 4x4": ["Journey"] } },
        "Fiat": { "Egea Cross": { "1.4 Fire 95 HP": ["Street", "Urban", "Lounge"] } },
        "Ford": { "Puma": { "1.0L EcoBoost 125 PS": ["Style", "ST-Line"] }, "Kuga": { "1.5L EcoBoost 120 PS": ["Style", "Titanium"] }, "Ranger": { "2.0L EcoBlue 205 PS": ["Wildtrak"] } },
        "Hyundai": { "Bayon": { "1.4 MPI 100 PS": ["Jump", "Style", "Elite"] }, "Tucson": { "1.6 T-GDI 180 PS": ["Prime", "Elite"] } },
        "Kia": { "Stonic": { "1.4L 100 PS": ["Cool", "Business", "Elegance"] }, "Sportage": { "1.6L T-GDI 150 PS": ["Cool", "Elegance"] } },
        "Land Rover": { "Defender": { "2.0 300 HP": ["S", "SE"] }, "Range Rover": { "3.0 440 HP": ["SE", "Autobiography"] } },
        "Mercedes-Benz": { "GLA": { "200": ["AMG"] }, "GLC": { "220 d 4MATIC": ["AMG"] } },
        "MG": { "ZS": { "1.5 VTi-TECH": ["Comfort", "Luxury"] }, "HS": { "1.5 T-GDI": ["Comfort", "Luxury"] } },
        "Nissan": { "Juke": { "1.0 DIG-T 115 PS": ["Tekna", "Platinum"] }, "Qashqai": { "1.3 DIG-T 158 PS": ["Tekna", "Skypack", "Platinum Premium"] } },
        "Opel": { "Crossland": { "1.2 130 HP": ["Essential", "Elegance"] }, "Mokka": { "1.2 130 HP": ["Elegance", "GS", "Ultimate"] } },
        "Peugeot": { "2008": { "1.2 PureTech 130 HP": ["Active Prime", "Allure", "GT"] }, "3008": { "1.5 BlueHDi 130 HP": ["Active Prime", "Allure", "GT"] } },
        "Renault": { "Captur": { "1.3 TCe 140 HP": ["Touch Plus", "Icon"] } },
        "Seat": { "Arona": { "1.0 EcoTSI 110 HP": ["Style", "FR"] }, "Ateca": { "1.5 EcoTSI 150 HP": ["Style", "FR"] } },
        "Skoda": { "Kamiq": { "1.0 TSI 110 PS": ["Elite", "Premium"] }, "Karoq": { "1.5 TSI 150 PS": ["Elite", "Premium"] } },
        "Suzuki": { "Vitara": { "1.4 Boosterjet Hybrid": ["GL Elegance", "GLX Premium"] } },
        "Toyota": { "Yaris Cross": { "1.5 Hybrid": ["Dream", "Flame X-Pack"] }, "C-HR": { "1.8 Hybrid": ["Passion", "Passion X-Pack"] } },
        "Volkswagen": { "T-Roc": { "1.5 TSI 150 PS": ["Life", "Style", "R-Line"] }, "Tiguan": { "1.5 TSI 150 PS": ["Life", "Elegance", "R-Line"] } },
    },
    "Motosiklet": {
        "Honda": { "PCX 125": { "125cc": ["Standart"] }, "Forza 250": { "250cc": ["Standart"] }, "Africa Twin": { "1100cc": ["Adventure Sports"] } },
        "Yamaha": { "NMAX 155": { "155cc": ["Standart"] }, "XMAX 250": { "250cc": ["Tech Max"] }, "Tenere 700": { "700cc": ["Standart"] } },
        "BMW Motorrad": { "R 1250 GS": { "1250cc": ["Adventure"] }, "F 850 GS": { "850cc": ["Standart"] } },
        "KTM": { "390 Duke": { "390cc": ["Standart"] }, "890 Adventure": { "890cc": ["R"] } },
        "Ducati": { "Multistrada V4": { "1158cc": ["S"] } },
    },
    "Ticari": {
        "Fiat": { "Fiorino": { "1.3 M.Jet": ["Pop", "Safeline", "Premio"] }, "Doblo": { "1.6 M.Jet": ["Safeline", "Premio Plus"] } },
        "Ford": { "Tourneo Courier": { "1.5L TDCi": ["Trend", "Deluxe", "Titanium"] }, "Transit Custom": { "2.0L EcoBlue": ["Trend"] } },
        "Peugeot": { "Rifter": { "1.5 BlueHDi": ["Allure", "GT"] } },
        "Volkswagen": { "Caddy": { "2.0 TDI": ["Impression", "Life", "Style"] } },
    },
    "Elektrikli Araçlar": {
        "Togg": { "T10X": { "V1 RWD": ["Standart Menzil"], "V2 RWD": ["Uzun Menzil"] } },
        "Tesla": { "Model Y": { "Arkadan İtiş": ["Standart"], "Long Range": ["Çift Motor AWD"], "Performance": ["Çift Motor AWD"] }, "Model 3": { "Arkadan İtiş": ["Standart"] } },
        "BMW": { "i4": { "eDrive40": ["M Sport"] }, "iX": { "xDrive40": ["First Edition"] } },
        "Hyundai": { "Ioniq 5": { "170 PS": ["Progressive"] } },
        "Kia": { "EV6": { "170 PS": ["Standart Range"] } },
        "Mercedes-Benz": { "EQA": { "250+": ["AMG+"] }, "EQB": { "250+": ["AMG+"] }, "EQC": { "400 4MATIC": ["AMG"] } },
        "MG": { "MG4": { "51 kWh": ["Comfort"], "64 kWh": ["Luxury"] } },
        "Renault": { "Zoe": { "80 kW": ["Intense"] } },
    }
};

